name: Deploy Node.js App

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to master branch11

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up SSH to Live Server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 18.212.27.181 >> ~/.ssh/known_hosts

    - name: Deploy on Live Server
      run: |
        ssh ubuntu@18.212.27.181 << 'EOF'
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/vijay  # Use deployment key to access repo
          cd /var/www/test_next
          git pull origin master
          npm install --production
          pm2 restart demo  # Restart Node.js app
        EOF
